# Autogenerated wrapper script for libLAS_jll for i686-w64-mingw32-cxx03
export liblas, liblas_c

using boost_jll
using GDAL_jll
using PROJ_jll
using libgeotiff_jll
JLLWrappers.@generate_wrapper_header("libLAS")
JLLWrappers.@declare_library_product(liblas, "liblas.dll")
JLLWrappers.@declare_library_product(liblas_c, "liblas_c.dll")
function __init__()
    JLLWrappers.@generate_init_header(boost_jll, GDAL_jll, PROJ_jll, libgeotiff_jll)
    JLLWrappers.@init_library_product(
        liblas,
        "bin\\liblas.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblas_c,
        "bin\\liblas_c.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
